apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-root-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: my-root-ca
  secretName: my-root-ca-secret
  issuerRef:
    name: selfsigned-root
    kind: ClusterIssuer

